import { Roboto } from "next/font/google";
import "./styles/globals.css";

import NavBar from "./components/navBar";
//import Footer from "./components/footer";

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${roboto.variable}`}>
      <body>
        <NavBar />
        {children}
        {/* <Footer /> */}
      </body>
    </html>
  );
}
